version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/teldrive/server
    restart: always
    container_name: teldrive
    volumes:
      - ./sessions:/app/sessions:rw
    env_file: .env
    ports:
      - 8000:8080