version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/teldrive/server:test
    restart: always
    container_name: server
    volumes:
      - ./sessions:/app/sessions:rw
      - ./database:/app/database
    env_file: .env
    ports:
      - 8080

  client:
    image: ghcr.io/divyam234/teldrive/client:latest
    restart: always
    container_name: client
    ports:
      - 3000
      
  haproxy:
    image: haproxy:latest
    volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    # ports:
    #   - 80:80
    #   - 443:443
    ports:
      - 8000:8000
    depends_on:
     - server
     - client