name: Build Postgres

on: 
  workflow_dispatch:
      
permissions: write-all

jobs:
  build-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Vars
        run: |
         echo "IMAGE=ghcr.io/${GITHUB_ACTOR,,}/postgres" >> $GITHUB_ENV
         
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/postgres
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE }}:latest,${{ env.IMAGE }}:16-alpine